# Generated by Django 3.0.6 on 2020-05-29 14:33

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to=posts.models.sheet_upload_location)),
                ('template', models.FileField(default=None, upload_to=posts.models.template_upload_location)),
                ('marker', models.ImageField(blank=True, null=True, upload_to=posts.models.template_upload_location)),
            ],
        ),
    ]
