# Generated by Django 3.0.6 on 2020-05-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='marker',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
